# Use an official Node runtime as a parent image
FROM cgr.dev/bp.com/node:22-dev

#need to be root to copy files around
USER root

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY ./package*.json ./

# Install the dependencies
RUN /usr/bin/npm install

# Copy the remaining application files to the working directory
COPY . .

# Build the application
RUN /usr/bin/npm run build

# Expose port 3000 for the application
EXPOSE 3000

# Start the application
CMD [ "/usr/bin/npm", "run", "start" ]
